import 'package:get/get.dart';

class AppLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'start_journey':
          'Start your journey with BORDERXCESS, your destination is just one touch away.',
      'login': 'Login',
      'register': 'Register',
      'faq_click_here': 'FAQ Click Here',
      'version': 'Version:',
      'lets_get_started': 'Let\'s get started by filling out the form below.',
      'name': 'Name',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'phone_number_format': 'Phone number must be in the format 60123456789',
      'password': 'Password',
      'password_format': 'Password must be at least 8 characters',
      'create_account': 'Create Account',
      'otp_verification': 'OTP Verification',
      'enter_otp': 'Enter four-digit OTP sent to your email',
      'otp_code': 'OTP Code',
      'enter_otp_code': 'Enter OTP Code',
      'request_new_otp': 'Request new OTP in',
      'verify_otp': 'Verify OTP',
      'welcome_back': 'Welcome back! Please login to your account',
      'forgot_password': 'Forgot Password',
      'dont_have_account': 'Don\'t have an account?',
      'sign_up': 'Sign up',
      'welcome_borderxcess': 'Welcome to BorderXcess',
      'ekyc': 'eKYC',
      'start_ekyc': 'Start your eKYC process to verify your identity',
      'passport_verification': 'Passport Verification',
      'capture_mrz':
          'Please capture the machine-readable zone (MRZ) of your passport front page.',
      'scan_passport': 'Scan Passport',
      'continue': 'Continue',
      'rescan': 'Rescan',
      'ekyc_form': 'eKYC Form',
      'full_name': 'Full Name',
      'country_code': 'Country Code',
      'dob': 'Date of Birth',
      'date_of_expiry': 'Date of Expiry',
      'document_number': 'Document Number',
      'document_type': 'Document Type',
      'mrz_type': 'MRZ Type',
      'nationality': 'Nationality',
      'optional_data': 'Optional Data',
      'gender': 'Gender',
      'dress_instructions':
          'Please wear suitable dress as the image will be used by Immigration Department for official purposes',
      'device_instructions':
          'Please make sure to hold the device at eye level to center your face.',
      'take_photo': 'Take a Photo',
      'profile_information': 'Profile Information',
      'save': 'Save',
      'individual': 'Individual',
      'group': 'Group',
      'mode_of_transport': 'Mode of Transport',
      'airplane': 'Airplane',
      'ferry_boat': 'Ferry/ Boat',
      'bus': 'Bus',
      'car': 'Car',
      'individual_qr': 'Individual QR',
      'individual_profile': 'Individual Profile',
      'passport_no': 'Passport No.',
      'tap_to_view': 'Tap view and generate your Individual QR Code',
      'individual_qr_code':
          'This is your individual QR code. You can use this QR code to access your account.',
    },
    'id': {
      'start_journey':
          'Mulai perjalanan Anda dengan BORDERXCESS, tujuan Anda hanya dalam satu sentuhan.',
      'login': 'Masuk',
      'register': 'Daftar',
      'faq_click_here': 'FAQ Klik di sini',
      'version': 'Versi:',
      'lets_get_started': 'Mari mulai dengan mengisi formulir di bawah ini.',
      'name': 'Nama',
      'email': 'Email',
      'phone_number': 'Nomor Telepon',
      'phone_number_format': 'Nomor telepon harus dalam format 60123456789',
      'password': 'Kata Sandi',
      'password_format': 'Kata sandi harus terdiri dari minimal 8 karakter',
      'create_account': 'Buat Akun',
      'otp_verification': 'Verifikasi OTP',
      'enter_otp': 'Masukkan kode OTP empat digit yang dikirim ke email Anda',
      'otp_code': 'Kode OTP',
      'enter_otp_code': 'Masukkan Kode OTP',
      'request_new_otp': 'Minta OTP baru dalam',
      'verify_otp': 'Verifikasi OTP',
      'welcome_back': 'Selamat datang kembali! Silakan masuk ke akun Anda',
      'forgot_password': 'Lupa Kata Sandi',
      'dont_have_account': 'Belum punya akun?',
      'sign_up': 'Daftar',
      'welcome_borderxcess': 'Selamat datang di BorderXcess',
      'ekyc': 'eKYC',
      'start_ekyc':
          'Mulai proses eKYC Anda untuk memverifikasi identitas Anda.',
      'passport_verification':
          'Mohon hadapkan machine-readable zone (MRZ) yang terdapat di halaman depan paspor Anda.',
      'scan_passport': 'Pindai Paspor',
      'continue': 'Lanjutkan',
      'rescan': 'Pindai Ulang',
      'ekyc_form': 'Formulir eKYC',
      'full_name': 'Nama Lengkap',
      'country_code': 'Kode Negara',
      'dob': 'Tanggal Lahir',
      'date_of_expiry': 'Tanggal Kedaluwarsa',
      'document_number': 'Nomor Dokumen',
      'document_type': 'Jenis Dokumen',
      'mrz_type': 'Jenis MRZ',
      'nationality': 'Kewarganegaraan',
      'optional_data': 'Data Opsional',
      'gender': 'Jenis Kelamin',
      'dress_instructions':
          'Mohon kenakan pakaian yang sesuai karena gambar ini akan digunakan oleh Departemen Imigrasi untuk keperluan resmi.',
      'device_instructions':
          'Pastikan Anda memegang perangkat sejajar dengan mata agar wajah Anda berada di tengah.',
      'take_photo': 'Ambil Potret Diri',
      'profile_information': 'Informasi Profil',
      'save': 'Simpan',
      'individual': 'Individu',
      'group': 'Grup',
      'mode_of_transport': 'Moda Transportasi',
      'airplane': 'Pesawat',
      'ferry_boat': 'Feri/Perahu',
      'bus': 'Bus',
      'car': 'Mobil',
      'individual_qr': 'QR Individu',
      'individual_profile': 'Profil Individu',
      'passport_no': 'Nomor Paspor',
      'tap_to_view': 'Ketuk "Lihat" dan buat Kode QR Individu Anda.',
      'individual_qr_code':
          'Ini adalah kode QR individu Anda. Anda dapat menggunakan kode QR ini untuk mengakses akun Anda.',
    },
    'es': {
      "start_journey":
          "Comienza tu viaje con BORDERXCESS, tu destino está a solo un toque de distancia.",
      "login": "Iniciar sesión",
      "register": "Registrarse",
      "faq_click_here": "Preguntas frecuentes Haz clic aquí",
      "version": "Versión:",
      "lets_get_started": "Comencemos completando el siguiente formulario.",
      "name": "Nombre",
      "email": "Correo electrónico",
      "phone_number": "Número de teléfono",
      "phone_number_format":
          "El número de teléfono debe tener el formato 60123456789",
      "password": "Contraseña",
      "password_format": "La contraseña debe tener al menos 8 caracteres",
      "create_account": "Crear cuenta",
      "otp_verification": "Verificación de OTP",
      "enter_otp":
          "Ingresa el código de cuatro dígitos enviado a tu correo electrónico.",
      "otp_code": "Código OTP",
      "enter_otp_code": "Ingresa el código OTP",
      "request_new_otp": "Solicitar un nuevo OTP en",
      "verify_otp": "Verificar OTP",
      "welcome_back":
          "¡Bienvenido de nuevo! Por favor, inicia sesión en tu cuenta.",
      "forgot_password": "¿Olvidaste tu contraseña?",
      "dont_have_account": "¿No tienes una cuenta?",
      "sign_up": "Regístrate",
      "welcome_borderxcess": "Bienvenido a BorderXcess",
      "ekyc": "eKYC",
      "start_ekyc": "Inicia tu proceso de eKYC para verificar tu identidad.",
      "passport_verification": "Verificación de Pasaporte",
      "capture_mrz":
          "Por favor, captura la zona de lectura mecánica (MRZ) de la página frontal de tu pasaporte.",
      "scan_passport": "Escanear pasaporte",
      "continue": "Continuar",
      "rescan": "Reescanear",
      "ekyc_form": "Formulario eKYC",
      "full_name": "Nombre completo",
      "country_code": "Código de país",
      "dob": "Fecha de nacimiento",
      "date_of_expiry": "Fecha de vencimiento",
      "document_number": "Número de documento",
      "document_type": "Tipo de documento",
      "mrz_type": "Tipo de MRZ",
      "nationality": "Nacionalidad",
      "optional_data": "Datos opcionales",
      "gender": "Género",
      "dress_instructions":
          "Por favor, usa vestimenta adecuada, ya que la imagen será utilizada por el Departamento de Inmigración con fines oficiales",
      "device_instructions":
          "Asegúrate de sostener el dispositivo a la altura de los ojos para centrar tu rostro.",
      "take_photo": "Tomar una foto",
      "profile_information": "Información del perfil",
      "save": "Guardar",
      "individual": "Individual",
      "group": "Grupo",
      "mode_of_transport": "Modo de transporte",
      "airplane": "Avión",
      "ferry_boat": "Ferry/ Barco",
      "bus": "Autobús",
      "car": "Coche",
      "individual_qr": "QR Individual",
      "individual_profile": "Perfil individual",
      "passport_no": "Número de pasaporte",
      "tap_to_view": "Toca \"ver\" y genera tu código QR individual",
      "individual_qr_code":
          "Este es tu código QR individual. Puedes usar este código QR para acceder a tu cuenta.",
    },
    // vietnamese
    'vi': {
      "start_journey":
          "Bắt đầu hành trình của bạn với BORDERXCESS, điểm đến chỉ cách bạn một chạm",
      "login": "Đăng nhập",
      "register": "Đăng ký",
      "faq_click_here": "FAQ Nhấp vào đây",
      "version": "Phiên bản:",
      "lets_get_started": "Hãy bắt đầu bằng cách điền vào biểu mẫu dưới đây.",
      "name": "Tên",
      "email": "Email",
      "phone_number": "Số điện thoại",
      "phone_number_format": "Số điện thoại phải ở định dạng 60123456789",
      "password": "Mật khẩu",
      "password_format": "Mật khẩu phải có ít nhất 8 ký tự",
      "create_account": "Tạo tài khoản",
      "otp_verification": "Xác minh",
      "enter_otp": "Nhập mã OTP gồm bốn chữ số đã được gửi đến email của bạn.",
      "otp_code": "Mã OTP",
      "enter_otp_code": "Nhập mã OTP",
      "request_new_otp": "Yêu cầu mã OTP mới trong",
      "verify_otp": "Xác minh mã OTP",
      "welcome_back":
          "Chào mừng trở lại! Vui lòng đăng nhập vào tài khoản của bạn.",
      "forgot_password": "Quên mật khẩu",
      "dont_have_account": "Chưa có tài khoản?",
      "sign_up": "Đăng ký",
      "welcome_borderxcess": "Chào mừng bạn đến với BorderXcess",
      "ekyc": "eKYC",
      "start_ekyc": "Bắt đầu quy trình eKYC của bạn để xác minh danh tính",
      "passport_verification": "Xác minh Hộ chiếu",
      "capture_mrz":
          "Vui lòng chụp khu vực có thể đọc bằng máy (MRZ) trên trang bìa hộ chiếu của bạn.",
      "scan_passport": "Quét hộ chiếu",
      "continue": "Tiếp tục",
      "rescan": "Quét lại",
      "ekyc_form": "Mẫu eKYC",
      "full_name": "Họ và tên",
      "country_code": "Mã quốc gia",
      "dob": "Ngày sinh",
      "date_of_expiry": "Ngày hết hạn",
      "document_number": "Số tài liệu",
      "document_type": "Loại tài liệu",
      "mrz_type": "Loại MRZ",
      "nationality": "Quốc tịch",
      "optional_data": "Dữ liệu tùy chọn",
      "gender": "Giới tính",
      "dress_instructions":
          "Vui lòng mặc trang phục phù hợp vì hình ảnh sẽ được sử dụng bởi Cục Di trú cho mục đích chính thức",
      "device_instructions":
          "Vui lòng chắc chắn giữ thiết bị ở mức mắt để căn chỉnh khuôn mặt của bạn",
      "take_photo": "Chụp ảnh",
      "profile_information": "Thông tin hồ sơ",
      "save": "Lưu",
      "individual": "Cá nhân",
      "group": "Nhóm",
      "mode_of_transport": "Phương tiện vận chuyển",
      "airplane": "Máy bay",
      "ferry_boat": "Phà/Thuyền",
      "bus": "Xe buýt",
      "car": "Xe ô tô",
      "individual_qr": "QR cá nhân",
      "individual_profile": "Hồ sơ cá nhân",
      "passport_no": "Số hộ chiếu",
      "tap_to_view": "Nhấn xem và tạo mã QR cá nhân của bạn",
      "individual_qr_code":
          "Đây là mã QR cá nhân của bạn. Bạn có thể sử dụng mã QR này để truy cập tài khoản của mình.",
    },
    // chinese mandarin
    'zh': {
      "start_journey": "开始您的旅程与 BORDERXCESS, 您的目的地触手可及",
      "login": "登录",
      "register": "注册",
      "faq_click_here": "FAQ 点击这里",
      "version": "版本:",
      "lets_get_started": "让我们通过填写下面的表格开始吧。",
      "name": "姓名",
      "email": "电子邮件",
      "phone_number": "电话号码",
      "phone_number_format": "电话号码必须为 60123456789 格式",
      "password": "密码",
      "password_format": "密码必须至少为 8 个字符",
      "create_account": "创建账户",
      "otp_verification": "OTP 验证",
      "enter_otp": "请输入发送到您电子邮件的四位数 OTP",
      "otp_code": "OTP 代码",
      "enter_otp_code": "请输入 OTP 代码",
      "request_new_otp": "请求新 OTP 在",
      "verify_otp": "验证 OTP",
      "welcome_back": "欢迎回来！请登录您的账户",
      "forgot_password": "忘记密码",
      "dont_have_account": "没有账户？",
      "sign_up": "注册",
      "welcome_borderxcess": "欢迎来到 BorderXcess",
      "ekyc": "电子 KYC",
      "start_ekyc": "开始您的电子 KYC 过程以验证您的身份",
      "passport_verification": "护照验证",
      "capture_mrz": "请拍摄您护照首页的机器可读区 (MRZ)。",
      "scan_passport": "扫描护照",
      "continue": "继续",
      "rescan": "重新扫描",
      "ekyc_form": "电子 KYC 表格",
      "full_name": "全名",
      "country_code": "国家代码",
      "dob": "出生日期",
      "date_of_expiry": "到期日期",
      "document_number": "文件号码",
      "document_type": "文件类型",
      "mrz_type": "MRZ 类型",
      "nationality": "国籍",
      "optional_data": "可选数据",
      "gender": "性别",
      "dress_instructions": "请穿着合适的服装，因为此照片将被移民局用于官方用途。",
      "device_instructions": "请确保将设备保持在眼睛水平，以便将您的面部居中。",
      "take_photo": "拍照",
      "profile_information": "个人资料",
      "save": "保存",
      "individual": "个人",
      "group": "团体",
      "mode_of_transport": "交通方式",
      "airplane": "飞机",
      "ferry_boat": "渡轮/船",
      "bus": "巴士",
      "car": "汽车",
      "individual_qr": "个人二维码",
      "individual_profile": "个人资料",
      "passport_no": "护照号码",
      "tap_to_view": "点击查看并生成您的个人二维码",
      "individual_qr_code": "这是您的个人二维码，您可以使用此二维码访问您的账户",
    },
    // thai
    'th': {
      "start_journey":
          "เริ่มการเดินทางของคุณกับ BORDERXCESS จุดหมายของคุณแค่เพียงการแตะครั้งเดียว",
      "login": "เข้าสู่ระบบ",
      "register": "สมัครสมาชิก",
      "faq_click_here": "คำถามที่พบบ่อย คลิกที่นี่",
      "version": "เวอร์ชัน:",
      "lets_get_started": "เริ่มต้นโดยการกรอกแบบฟอร์มด้านล่าง",
      "name": "ชื่อ",
      "email": "อีเมล",
      "phone_number": "หมายเลขโทรศัพท์",
      "phone_number_format": "หมายเลขโทรศัพท์ต้องเป็นรูปแบบ 60123456789",
      "password": "รหัสผ่าน",
      "password_format": "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
      "create_account": "สร้างบัญชี",
      "otp_verification": "การยืนยัน OTP",
      "enter_otp": "กรอกรหัส OTP สี่หลักที่ส่งไปยังอีเมลของคุณ",
      "otp_code": "รหัส OTP",
      "enter_otp_code": "กรอกรหัส OTP",
      "request_new_otp": "ขอรหัส OTP ใหม่ใน",
      "verify_otp": "ยืนยัน OTP",
      "welcome_back": "ยินดีต้อนรับกลับ! กรุณาเข้าสู่ระบบบัญชีของคุณ",
      "forgot_password": "ลืมรหัสผ่าน",
      "dont_have_account": "ยังไม่มีบัญชี?",
      "sign_up": "สมัครสมาชิก",
      "welcome_borderxcess": "ยินดีต้อนรับสู่ BorderXcess",
      "ekyc": "eKYC",
      "start_ekyc": "เริ่มกระบวนการ eKYC ของคุณเพื่อยืนยันตัวตน",
      "passport_verification": "การตรวจสอบพาสปอร์ต",
      "capture_mrz":
          "กรุณาถ่ายภาพโซนที่อ่านได้โดยเครื่อง (MRZ) บนหน้าปกของพาสปอร์ต",
      "scan_passport": "สแกนพาสปอร์ต",
      "continue": "ดำเนินการต่อ",
      "rescan": "สแกนใหม่",
      "ekyc_form": "แบบฟอร์ม eKYC",
      "full_name": "ชื่อเต็ม",
      "country_code": "รหัสประเทศ",
      "dob": "วันเกิด",
      "date_of_expiry": "วันหมดอายุ",
      "document_number": "หมายเลขเอกสาร",
      "document_type": "ประเภทเอกสาร",
      "mrz_type": "ประเภท MRZ",
      "nationality": "สัญชาติ",
      "optional_data": "ข้อมูลเพิ่มเติม",
      "gender": "เพศ",
      "dress_instructions":
          "กรุณาสวมเสื้อผ้าที่เหมาะสม เนื่องจากภาพนี้จะถูกนำไปใช้โดยกรมการตรวจคนเข้าเมืองเพื่อวัตถุประสงค์ทางการ",
      "device_instructions":
          "โปรดมั่นใจว่าได้ถืออุปกรณ์ในระดับสายตาเพื่อให้อยู่กลางใบหน้า",
      "take_photo": "ถ่ายภาพ",
      "profile_information": "ข้อมูลโปรไฟล์",
      "save": "บันทึก",
      "individual": "บุคคล",
      "group": "กลุ่ม",
      "mode_of_transport": "วิธีการเดินทาง",
      "airplane": "เครื่องบิน",
      "ferry_boat": "เรือเฟอร์รี่/เรือ",
      "bus": "รถบัส",
      "car": "รถยนต์",
      "individual_qr": "QR ส่วนบุคคล",
      "individual_profile": "โปรไฟล์ส่วนบุคคล",
      "passport_no": "หมายเลขพาสปอร์ต",
      "tap_to_view": "แตะเพื่อดูและสร้าง QR Code ส่วนบุคคลของคุณ",
      "individual_qr_code":
          "นี่คือ QR Code ส่วนบุคคลของคุณ คุณสามารถใช้ QR Code นี้ในการเข้าสู่ระบบบัญชีของคุณ",
    },
    // korean
    'ko': {
      "start_journey": "BORDERXCESS 와 함께 여행을 시작하세요. 목적지는 손끝 하나로 다가옵니다.",
      "login": "로그인",
      "register": "회원가입",
      "faq_click_here": "FAQ 여기를 클릭하세요",
      "version": "버전:",
      "lets_get_started": "아래 양식을 작성하여 시작하세요.",
      "name": "이름",
      "email": "이메일",
      "phone_number": "전화번호",
      "phone_number_format": "전화번호는 60123456789 형식이어야 합니다.",
      "password": "비밀번호",
      "password_format": "비밀번호는 최소 8자 이상이어야 합니다.",
      "create_account": "계정 생성",
      "otp_verification": "OTP 인증",
      "enter_otp": "이메일로 전송된 네 자릿수 OTP를 입력하세요.",
      "otp_code": "OTP 코드",
      "enter_otp_code": "OTP 코드를 입력하세요.",
      "request_new_otp": "새 OTP 요청 (시간 제한)",
      "verify_otp": "OTP 인증",
      "welcome_back": "다시 오신 것을 환영합니다! 계정에 로그인하세요.",
      "forgot_password": "비밀번호를 잊으셨나요?",
      "dont_have_account": "계정이 없으신가요?",
      "sign_up": "회원가입",
      "welcome_borderxcess": "BorderXcess에 오신 것을 환영합니다.",
      "ekyc": "eKYC",
      "start_ekyc": "귀하의 신원을 확인하기 위해 eKYC 프로세스를 시작하세요.",
      "passport_verification": "여권 인증",
      "capture_mrz": "여권 첫 페이지의 기계 판독 구역(MRZ)을 촬영해 주세요.",
      "scan_passport": "여권 스캔",
      "continue": "계속",
      "rescan": "다시 스캔",
      "ekyc_form": "eKYC 양식",
      "full_name": "전체 이름",
      "country_code": "국가 코드",
      "dob": "생년월일",
      "date_of_expiry": "만료일",
      "document_number": "문서 번호",
      "document_type": "문서 유형",
      "mrz_type": "MRZ 유형",
      "nationality": "국적",
      "optional_data": "선택 사항",
      "gender": "성별",
      "dress_instructions": "적합한 복장을 착용해 주세요. 이 이미지는 이민국에서 공식 용도로 사용됩니다.",
      "device_instructions": "기기를 눈높이에 맞추어 얼굴을 중앙에 오도록 해 주세요.",
      "take_photo": "사진 찍기",
      "profile_information": "프로필 정보",
      "save": "저장",
      "individual": "개인",
      "group": "단체",
      "mode_of_transport": "교통 수단",
      "airplane": "비행기",
      "ferry_boat": "페리/보트",
      "bus": "버스",
      "car": "자동차",
      "individual_qr": "개인 QR",
      "individual_profile": "개인 프로필",
      "passport_no": "여권 번호",
      "tap_to_view": "보기 탭을 눌러 개인 QR 코드를 생성하세요.",
      "individual_qr_code":
          "이것은 귀하의 개인 QR 코드입니다. 이 QR 코드를 사용하여 귀하의 계정에 접근할 수 있습니다.",
    },
    'ja': {
      "start_journey": "BORDERXCESS で旅を始めましょう。目的地はワンタッチで到達できます。",
      "login": "ログイン",
      "register": "登録",
      "faq_click_here": "FAQ こちらをクリック",
      "version": "バージョン:",
      "lets_get_started": "以下のフォームに記入して始めましょう。",
      "name": "名前",
      "email": "メールアドレス",
      "phone_number": "電話番号",
      "phone_number_format": "電話番号は60123456789の形式で入力してください。",
      "password": "パスワード",
      "password_format": "パスワードは8文字以上でなければなりません。",
      "create_account": "アカウント作成",
      "otp_verification": "OTP認証",
      "enter_otp": "メールで送信された4桁のOTPを入力してください。",
      "otp_code": "OTPコード",
      "enter_otp_code": "OTPコードを入力してください。",
      "request_new_otp": "新しいOTPを要求する（時間制限）",
      "verify_otp": "OTPを確認",
      "welcome_back": "お帰りなさい！アカウントにログインしてください。",
      "forgot_password": "パスワードを忘れた場合",
      "dont_have_account": "アカウントをお持ちでないですか？",
      "sign_up": "サインアップ",
      "welcome_borderxcess": "XXXXXXへようこそ",
      "ekyc": "eKYC",
      "start_ekyc": "あなたの身元を確認するためにeKYCプロセスを開始してください",
      "passport_verification": "パスポート認証",
      "capture_mrz": "パスポートの表紙にある機械読み取りゾーン（MRZ）を撮影してください。",
      "scan_passport": "パスポートをスキャン",
      "continue": "続ける",
      "rescan": "再スキャン",
      "ekyc_form": "eKYCフォーム",
      "full_name": "フルネーム",
      "country_code": "国コード",
      "dob": "生年月日",
      "date_of_expiry": "有効期限",
      "document_number": "書類番号",
      "document_type": "書類タイプ",
      "mrz_type": "MRZタイプ",
      "nationality": "国籍",
      "optional_data": "オプションデータ",
      "gender": "性別",
      "dress_instructions": "適切な服装を着用してください。画像は移民局の公式目的で使用されます。",
      "device_instructions": "顔を中央に合わせるために、デバイスを目の高さで保持してください。",
      "take_photo": "写真を撮る",
      "profile_information": "プロフィール情報",
      "save": "保存",
      "individual": "個人",
      "group": "グループ",
      "mode_of_transport": "交通手段",
      "airplane": "飛行機",
      "ferry_boat": "フェリー/ボート",
      "bus": "バス",
      "car": "車",
      "individual_qr": "個人QR",
      "individual_profile": "個人プロフィール",
      "passport_no": "パスポート番号",
      "tap_to_view": "表示をタップして個人QRコードを生成してください。",
      "individual_qr_code": "これがあなたの個人QRコードです。このQRコードを使用してアカウントにアクセスできます。",
    },
    // krygyz
    'ky': {
      "start_journey":
          "BORDERXCESS менен саяхатыңызды баштаңыз. Мақсатка бир гана түртүп жетсеңиз болот.",
      "login": "Кирүү",
      "register": "Катталуу",
      "faq_click_here": "Часто Суроолорго жооп берүүнү ушул жерден кириңиз",
      "version": "Басылма:",
      "lets_get_started": "Төмөнкү форманы толтуруп баштаңыз.",
      "name": "Аты-жөнү",
      "email": "Электрондук почта",
      "phone_number": "Телефон номери",
      "phone_number_format":
          "Телефон номери 60123456789 форматында болушу керек.",
      "password": "Жупуну сөз",
      "password_format": "Жупуну сөз минимум 8 тамга болушу керек.",
      "create_account": "Аккаунт түзүү",
      "otp_verification": "OTP текшерүү",
      "enter_otp":
          "Электрондук почтаңызга жөнөтүлгөн төрт сандык OTP кодун киргизиңиз.",
      "otp_code": "OTP код",
      "enter_otp_code": "OTP кодун киргизиңиз.",
      "request_new_otp": "Жаңы OTP суроо (мааниси бар убакыт)",
      "verify_otp": "OTP текшерүү",
      "welcome_back": "Кайрадан кош келдиңиз! Аккаунтка кирүү.",
      "forgot_password": "Паролду унуттум?",
      "dont_have_account": "Аккаунтуңуз жокпу?",
      "sign_up": "Катталуу",
      "welcome_borderxcess": "XXXXXXге кош келдиңиз",
      "ekyc": "eKYC",
      "start_ekyc": "Танууну текшерүү үчүн eKYC процессин баштаңыз",
      "passport_verification": "Паспортту текшерүү",
      "capture_mrz":
          "Паспорттун мурунку бетиндеги MRZ аймагынын сүрөтүн чабыңыз.",
      "scan_passport": "Паспортту сканерден өткөрүңүз",
      "continue": "Жалпы",
      "rescan": "Кайра сканерден өткөрүңүз",
      "ekyc_form": "eKYC Формасы",
      "full_name": "Толук аты-жөнү",
      "country_code": "Өлкөнүн коду",
      "dob": "Туулган күнү",
      "date_of_expiry": "Жарамдуулугунун мөөнөтү",
      "document_number": "Документтин номери",
      "document_type": "Документтин түрү",
      "mrz_type": "MRZ түрү",
      "nationality": "Жарандыгы",
      "optional_data": "Колдонмонун маалыматтары",
      "gender": "Жынысы",
      "dress_instructions":
          "Туура кийим кийишиңизди сураныч. Бул сүрөттү иммиграция кызматкерлери үчүн расмий максатта колдонуу болот.",
      "device_instructions":
          "Сүрөттү тартып жатканда, түзмөктү көз деңгээлине карата алып туруңуз.",
      "take_photo": "Сүрөттү тартыңыз",
      "profile_information": "Профиль маалыматы",
      "save": "Сактоо",
      "individual": "Жеке",
      "group": "Топ",
      "mode_of_transport": "Көчмөн жолун тандоо",
      "airplane": "Самолет",
      "ferry_boat": "Паром/Кемелер",
      "bus": "Автобус",
      "car": "Унаа",
      "individual_qr": "Жеке QR",
      "individual_profile": "Жеке Профиль",
      "passport_no": "Паспорт номери",
      "tap_to_view": "Жеке QR кодду түзүү үчүн көрүү баскычын басыңыз.",
      "individual_qr_code":
          "Бул сиздин жеке QR кодуңуз. Сиз ушул QR кодду колдонуп аккаунтуңузга кире аласыз.",
    },
    'ru': {
      "start_journey":
          "Начните ваше путешествие с BORDERXCESS. Ваша цель - всего лишь одно прикосновение.",
      "login": "Войти",
      "register": "Регистрация",
      "faq_click_here": "Часто задаваемые вопросы, нажмите здесь",
      "version": "Версия:",
      "lets_get_started": "Начните с заполнения формы ниже.",
      "name": "Имя",
      "email": "Электронная почта",
      "phone_number": "Номер телефона",
      "phone_number_format":
          "Номер телефона должен быть в формате 60123456789.",
      "password": "Пароль",
      "password_format": "Пароль должен содержать минимум 8 символов.",
      "create_account": "Создать аккаунт",
      "otp_verification": "Подтверждение OTP",
      "enter_otp":
          "Введите четырехзначный OTP код, отправленный на вашу электронную почту.",
      "otp_code": "OTP код",
      "enter_otp_code": "Введите OTP код.",
      "request_new_otp": "Запросить новый OTP (ограничение по времени)",
      "verify_otp": "Подтвердить OTP",
      "welcome_back": "С возвращением! Пожалуйста, войдите в ваш аккаунт.",
      "forgot_password": "Забыли пароль?",
      "dont_have_account": "Нет аккаунта?",
      "sign_up": "Зарегистрироваться",
      "welcome_borderxcess": "Добро пожаловать в XXXXXX",
      "ekyc": "eKYC",
      "start_ekyc": "Начните процесс eKYC для подтверждения вашей личности",
      "passport_verification": "Проверка паспорта",
      "capture_mrz":
          "Пожалуйста, сделайте снимок зоны машинного считывания (MRZ) на обложке паспорта.",
      "scan_passport": "Сканировать паспорт",
      "continue": "Продолжить",
      "rescan": "Пересканировать",
      "ekyc_form": "Форма eKYC",
      "full_name": "Полное имя",
      "country_code": "Код страны",
      "dob": "Дата рождения",
      "date_of_expiry": "Дата окончания срока действия",
      "document_number": "Номер документа",
      "document_type": "Тип документа",
      "mrz_type": "Тип MRZ",
      "nationality": "Гражданство",
      "optional_data": "Дополнительные данные",
      "gender": "Пол",
      "dress_instructions":
          "Пожалуйста, наденьте соответствующую одежду. Это изображение будет использовано иммиграционной службой для официальных целей.",
      "device_instructions":
          "Пожалуйста, держите устройство на уровне глаз, чтобы лицо было в центре.",
      "take_photo": "Сделать фото",
      "profile_information": "Информация профиля",
      "save": "Сохранить",
      "individual": "Индивидуальный",
      "group": "Группа",
      "mode_of_transport": "Выбор способа транспортировки",
      "airplane": "Самолет",
      "ferry_boat": "Паром/Корабль",
      "bus": "Автобус",
      "car": "Автомобиль",
      "individual_qr": "Личный QR",
      "individual_profile": "Личный профиль",
      "passport_no": "Номер паспорта",
      "tap_to_view": "Нажмите для просмотра и создания вашего личного QR кода.",
      "individual_qr_code":
          "Это ваш личный QR код. Вы можете использовать этот код для доступа в ваш аккаунт.",
    },
  };
}
